title: Still200 Integration Guide
description: Add uptime monitoring to your API in under 5 minutes.

remote_theme: just-the-docs/just-the-docs

nav_enabled: true
heading_anchors: true
footer_content: 'Copyright &copy; 2026 <a href="https://byteslab.io">Bytes Lab</a>'